version: '3.7'

services:
    homeassistant-checkconfig:
        image: homeassistant/amd64-addon-check_config
        working_dir: "//c/temp/ha-dev/checkconfig-docker"
        volumes:
        - type: bind
          source: "./options.json"
          target: "/data/options.json"
          read_only: true
        - type: bind
          source: "../s13-hass"
          target: "/config"
          read_only: true
