version: '3'

services:
    s13-hass-check_config:
        image: censored/hassio-addon-amd64-censored_check_config
        working_dir: "//C/temp/ha-dev/check_config/"
        volumes:
          - "./options.json:/data/options.json"
          - "../homeassistant:/config"
